CREATE TABLE `parser/det/teztour` (
    hotel_id int,
    hotel_rating double,
    currency_code double,
    latitude double,
    longitude double,
    price double,
    num_stars double,
    country_name utf8,
    is_flight_included bool,
    room_type utf8,
    mealplan utf8,
    preview_img utf8,
    title utf8,
    price_dollars double,
    price_euros double,
    location_name utf8,
    beach_line int,
    is_free_internet bool,
    airport_distance double,
    num_nights int,
    start_date date,
    end_date date,
    sand_beach_flg bool,
    link Utf8,
    website Utf8,
    offer_hash Utf8,
    key Utf8,
    bucket Utf8,
    parsing_id Utf8,
    row_id Utf8,
    row_extracted_dttm_utc datetime,
    created_dttm_utc datetime,
    PRIMARY KEY (parsing_id, row_id, row_extracted_dttm_utc) 
);