CREATE TABLE `parser/det/travelata` (
    title utf8,
    num_stars int,
    flag_less_places bool,
    location_name Utf8,
    country_name Utf8,
    rating double,
    num_reviews int,
    orders_count int,
    oil_tax_value double,
    hotel_id int,
    price double,
    num_people int,
    start_date date,
    end_date date,
    airport_distance double,
    beach_distance double,
    wifi_option Utf8,
    condi_option Utf8,
    num_nights int,
    is_flight_included bool,
    beach_line int,
    sand_beach_flg bool,
    pebble_beach_flg bool,
    beach_options Utf8,
    link Utf8,
    website Utf8,
    offer_hash Utf8,
    key Utf8,
    bucket Utf8,
    parsing_id Utf8,
    row_id Utf8,
    row_extracted_dttm_utc datetime,
    created_dttm_utc datetime,
    PRIMARY KEY (parsing_id, row_extracted_dttm_utc, row_id) 
);